"""meeting_notes

Revision ID: 0001
Revises:
Create Date: 2026-09-18 10:44:40.879095

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcripts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_name", sa.String(length=200), nullable=False),
        sa.Column("meeting_title", sa.String(length=300), nullable=False),
        sa.Column("meeting_date", sa.Date(), nullable=True),
        sa.Column("transcript_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcripts")),
    )
    op.create_index("ix_transcripts_created_at", "transcripts", ["created_at"], unique=False)
    op.create_table(
        "meeting_summaries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("transcript_id", sa.UUID(), nullable=False),
        sa.Column("executive_summary", sa.Text(), nullable=False),
        sa.Column("key_decisions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("action_items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("llm_model", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.id"],
            name=op.f("fk_meeting_summaries_transcript_id_transcripts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_summaries")),
        sa.UniqueConstraint("transcript_id", name=op.f("uq_meeting_summaries_transcript_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meeting_summaries")
    op.drop_index("ix_transcripts_created_at", table_name="transcripts")
    op.drop_table("transcripts")
    # ### end Alembic commands ###
